// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTCNj7-RSwTwsbwYqFuFO7rlsavY7wfIY',
    appId: '1:1062251410883:web:166215fa71d3d931f93976',
    messagingSenderId: '1062251410883',
    projectId: 'login-page-635b8',
    authDomain: 'login-page-635b8.firebaseapp.com',
    storageBucket: 'login-page-635b8.firebasestorage.app',
    measurementId: 'G-CCFNN0VYPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkLPmvpx8BREyLf7t03JzHLdLHp4FrUbY',
    appId: '1:1062251410883:android:b042e0a99829c4dcf93976',
    messagingSenderId: '1062251410883',
    projectId: 'login-page-635b8',
    storageBucket: 'login-page-635b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuwxAG2t1T5lWDxY0x-KaHyaF7wlLvjHs',
    appId: '1:1062251410883:ios:91305a348ccb429af93976',
    messagingSenderId: '1062251410883',
    projectId: 'login-page-635b8',
    storageBucket: 'login-page-635b8.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuwxAG2t1T5lWDxY0x-KaHyaF7wlLvjHs',
    appId: '1:1062251410883:ios:91305a348ccb429af93976',
    messagingSenderId: '1062251410883',
    projectId: 'login-page-635b8',
    storageBucket: 'login-page-635b8.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTCNj7-RSwTwsbwYqFuFO7rlsavY7wfIY',
    appId: '1:1062251410883:web:f2aabc80a815d1d5f93976',
    messagingSenderId: '1062251410883',
    projectId: 'login-page-635b8',
    authDomain: 'login-page-635b8.firebaseapp.com',
    storageBucket: 'login-page-635b8.firebasestorage.app',
    measurementId: 'G-5SSQRJZ5NB',
  );
}
